name: Bug Report
description: Report a bug or issue with a calculator
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.

  - type: input
    id: calculator
    attributes:
      label: Calculator Name
      description: Which calculator has the issue?
      placeholder: e.g., BMI Calculator
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What category is the calculator in?
      options:
        - Basic
        - Finance
        - Health
        - Sports
        - Statistics
        - Math
        - Education
        - Construction
        - Science
        - Internet Speed
        - Time
        - Food
        - Everyday
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: The calculator shows incorrect results when...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Enter values '....'
        3. Click on '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: The calculator should display...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Instead, it shows...
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      placeholder: e.g., Chrome 120, Firefox 121, Safari 17
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      placeholder: e.g., macOS 14.0, Windows 11, Ubuntu 22.04
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: Device Type
      options:
        - Desktop
        - Tablet
        - Mobile
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots if applicable (drag and drop images here)
      placeholder: Drag and drop screenshots here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: This happens only when...
